image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    visibility: public

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      python -m scripts.install
      gp sync-done deps
    command: pipenv run functions-framework --target main --debug
  - init: gp sync-await deps

vscode:
  extensions:
    - ms-python.python
    - streetsidesoftware.code-spell-checker
    - mikestead.dotenv
    - ms-azuretools.vscode-docker
    - github.vscode-pull-request-github
    - eamodio.gitlens
    - tabnine.tabnine-vscode
    - gruntfuggly.todo-tree
    - redhat.vscode-yaml
